services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: 'news-parser-db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - 3306:3306